##  Recurrent Neural Networks (RNNs)

### Introduction to RNN

#### What is a Recurrent Neural Network (RNN)?

A Recurrent Neural Network (RNN) is a type of artificial neural network designed for processing sequences of data. 

Unlike traditional feedforward neural networks, RNNs have connections that form directed cycles, allowing them to maintain a hidden state that can capture information about previous inputs in the sequence. 

This makes RNNs particularly well-suited for tasks where the order of the data is important, such as 

- Time-Series Prediction (e.g., stock prices, weather forecasting)
- Natural Language Processing (NLP) (e.g., machine translation, sentiment analysis)
- Speech Recognition (e.g., voice assistants)
- Music Generation (e.g., composing melodies)

Key characteristics of RNNs include:
- **Sequential Data Processing**: 
    - RNNs process input data in a sequential manner, one element at a time, while maintaining a hidden state that carries information from previous time steps.
    - Processes input data in a time-dependent manner.
- **Memory of Past Inputs**: 
    - Uses hidden states to retain past information.
- **Weight Sharing**:
    - The same weights are used at every time step, reducing the number of trainable parameters.
- **Backpropagation Through Time (BPTT)**: 
    - Training RNNs involves a variant of the backpropagation algorithm called Backpropagation Through Time, which accounts for the sequential nature of the data.

However, standard RNNs can struggle with learning long-term dependencies due to issues like vanishing and exploding gradients. To address these challenges, more advanced variants such as Long Short-Term Memory (LSTM) networks and Gated Recurrent Units (GRUs) have been developed.

**Differences Between Feedforward Networks and RNNs**



| Feature                        | Feedforward Networks                          | Recurrent Neural Networks (RNNs)               |
|--------------------------------|-----------------------------------------------|------------------------------------------------|
| Data Processing                | Processes input data all at once              | Processes input data sequentially              |
| Memory                         | No memory of past inputs                      | Maintains hidden state to remember past inputs |
| Weight Sharing                 | Different weights for each layer              | Same weights used at every time step           |
| Suitable for                   | Static data (e.g., images)                    | Sequential data (e.g., time series, text)      |
| Training Algorithm             | Standard backpropagation                      | Backpropagation Through Time (BPTT)            |
| Long-Term Dependencies         | Not suitable                                  | Can struggle, but improved with LSTM/GRU       |

#### Core Concepts of RNN

1. **Hidden State**: 
    - The hidden state is a key component of RNNs that allows them to maintain information about previous inputs in the sequence. 
    - It is updated at each time step based on the current input and the previous hidden state.

2. **Input Sequence**: 
    - RNNs process data as a sequence of inputs, where each element in the sequence is fed into the network one at a time. 
    - The order of the inputs is crucial for capturing temporal dependencies.

3. **Output Sequence**: 
    - Depending on the task, RNNs can produce an output at each time step or only at the final time step. 
    - The output can be a sequence of predictions or a single prediction based on the entire input sequence.

4. **Weights and Biases**: 
    - RNNs use the same set of weights and biases at each time step, which allows them to generalize across different positions in the sequence. 
    - This weight sharing reduces the number of parameters and helps in learning temporal patterns.

5. **Activation Function**: 
    - The activation function (e.g., tanh, ReLU) is applied to the hidden state to introduce non-linearity into the model, enabling it to learn complex patterns in the data.

6. **Backpropagation Through Time (BPTT)**: 
    - BPTT is a variant of the backpropagation algorithm used to train RNNs. 
    - It involves unrolling the network through time and computing gradients for each time step, which are then used to update the weights and biases.

7. **Long-Term Dependencies**: 
    - Standard RNNs can struggle with learning long-term dependencies due to issues like vanishing and exploding gradients. Advanced variants like LSTM and GRU are designed to address these challenges by incorporating gating mechanisms that regulate the flow of information.



**Recurrent Neurons**:
- Recurrent neurons are the fundamental building blocks of RNNs.
- Unlike traditional neurons, recurrent neurons have connections that loop back to themselves, allowing them to maintain a hidden state that captures information from previous time steps.
- This feedback loop enables the network to process sequences of data and learn temporal dependencies.

<img src='https://media.geeksforgeeks.org/wp-content/uploads/20241030134529497963/recurrent-neuron.png' alt='recuurent_neuron'></img>


**RNN Unfolding**:
- RNN unfolding refers to the process of unrolling the recurrent network through time.
- During training, the RNN is unfolded to create a sequence of copies of the network, one for each time step in the input sequence.
- Each copy shares the same weights and biases but processes a different element of the input sequence.
- The hidden state is passed from one time step to the next, allowing the network to maintain information about previous inputs.
- Unfolding the RNN is essential for applying the Backpropagation Through Time (BPTT) algorithm, which computes gradients for each time step and updates the weights accordingly.

<img src='https://media.geeksforgeeks.org/wp-content/uploads/20231204131012/Unfolding-660.png' alt='recuurent_neuron'></img>

### RNN Architecture

#### How RNN works?

Input Layer

- Receives sequential input data X = (x1, x2,...,xT).
- Each xt represents an element in the sequence at time step t.

In RNNs, the hidden state \( H_i \) is calculated for every input \( X_i \) to retain sequential dependencies. The computations follow these core formulas:

1. **Hidden State Update**:
\[ H_i = f(W_{hx} X_i + W_{hh} H_{i-1} + b_h) \]
    - \( W_{hx} \): Weight matrix for input to hidden state
    - \( W_{hh} \): Weight matrix for hidden state to hidden state
    - \( b_h \): Bias term
    - \( f \): Activation function (e.g., tanh, ReLU)

2. **Output Calculation**:
\[ O_i = g(W_{ho} H_i + b_o) \]
    - \( W_{ho} \): Weight matrix for hidden state to output
    - \( b_o \): Bias term
    - \( g \): Activation function for output (e.g., softmax for classification tasks)

#### Forward Propagation in RNNs

Forward propagation in RNNs involves processing an input sequence step-by-step while maintaining a hidden state that carries past information. 

- At time step t, the RNN takes input xt and previous hidden state ht−1.
- Computes the new hidden state ht.
- Generates an output yt.
- Repeats for all time steps.

In [40]:
import numpy as np

# Initialize RNN parameters
input_size = 3   # Input vector size
hidden_size = 5  # Hidden state size
output_size = 2  # Output size
seq_length = 4   # Number of time steps

# Randomly initialize weights and biases
np.random.seed(42)
W_x = np.random.randn(hidden_size, input_size)   # Input to hidden weights
W_h = np.random.randn(hidden_size, hidden_size)  # Hidden to hidden weights
W_y = np.random.randn(output_size, hidden_size)  # Hidden to output weights
b_h = np.random.randn(hidden_size, 1)            # Bias for hidden state
b_y = np.random.randn(output_size, 1)            # Bias for output

# Input sequence (4 time steps, batch size = 1)
X = np.random.randn(seq_length, input_size, 1)

# Initialize hidden state
h_t = np.zeros((hidden_size, 1))

# Forward propagation
outputs = []
for t in range(seq_length):
    h_t = np.tanh(np.dot(W_x, X[t]) + np.dot(W_h, h_t) + b_h)  # Hidden state update
    y_t = np.dot(W_y, h_t) + b_y  # Output calculation
    outputs.append(y_t)

# Print results
print("Final Hidden State:\n", h_t)
print("Outputs at each time step:\n", outputs)

Final Hidden State:
 [[ 0.95516432]
 [-0.99182894]
 [-0.03554066]
 [-0.99213409]
 [-0.12484929]]
Outputs at each time step:
 [array([[ 2.70878155],
       [-0.35994001]]), array([[ 0.41051732],
       [-3.81326106]]), array([[1.45961374],
       [1.14008039]]), array([[ 1.95410691],
       [-1.2282841 ]])]


#### Custom RNN Cell Implementation (NumPy)

In [41]:
import numpy as np

class CustomRNN:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # Initialize weights
        np.random.seed(42)  # For reproducibility
        self.W_xh = np.random.randn(hidden_size, input_size)   # Input to hidden weights
        self.W_hh = np.random.randn(hidden_size, hidden_size)  # Hidden to hidden weights
        self.W_hy = np.random.randn(output_size, hidden_size)  # Hidden to output weights
        self.b_h = np.random.randn(hidden_size, 1)            # Bias for hidden state
        self.b_y = np.random.randn(output_size, 1)            # Bias for output

    def forward(self, X):
        """
        X: Input sequence of shape (seq_length, input_size, 1)
        """
        seq_length = X.shape[0]
        h_t = np.zeros((self.hidden_size, 1))  # Initialize hidden state
        
        outputs = []
        for t in range(seq_length):
            h_t = np.tanh(np.dot(self.W_xh, X[t]) + np.dot(self.W_hh, h_t) + self.b_h)  # Update hidden state
            y_t = np.dot(self.W_hy, h_t) + self.b_y  # Compute output
            outputs.append(y_t)
        
        return np.array(outputs), h_t  # Return outputs and final hidden state

# Define input, hidden, and output sizes
input_size = 3
hidden_size = 5
output_size = 2
seq_length = 4

# Initialize RNN
rnn = CustomRNN(input_size, hidden_size, output_size)

# Create a sample input sequence
X = np.random.randn(seq_length, input_size, 1)

# Perform forward pass
outputs, final_hidden = rnn.forward(X)

print("Final Hidden State:\n", final_hidden)
print("Outputs at each time step:\n", outputs)

Final Hidden State:
 [[ 0.95516432]
 [-0.99182894]
 [-0.03554066]
 [-0.99213409]
 [-0.12484929]]
Outputs at each time step:
 [[[ 2.70878155]
  [-0.35994001]]

 [[ 0.41051732]
  [-3.81326106]]

 [[ 1.45961374]
  [ 1.14008039]]

 [[ 1.95410691]
  [-1.2282841 ]]]


#### Backpropagation Through Time (BPTT) in RNNs

During forward propagation, an RNN processes a sequence step by step, maintaining hidden states.

During backward propagation, errors from the output layer are propagated backward through time to update the weights.
- Loss Function (e.g., Mean Squared Error for regression, Cross-Entropy for classification)

Backpropagation Through Time (BPTT) is an extension of the backpropagation algorithm for training recurrent neural networks (RNNs). Here's a brief explanation of the gradient calculation in BPTT:

**1. Output Layer Gradient**
    - The gradient of the loss with respect to the output layer is calculated first. This is similar to the standard backpropagation in feedforward neural networks.

        # Assuming L is the loss, y is the output, and y_hat is the predicted output
        dL_dy_hat = y_hat - y



**2. Hidden State Gradient (Recursive)**
    - The gradient of the loss with respect to the hidden state is calculated recursively. This involves propagating the gradients backward through time.

        # Assuming h_t is the hidden state at time t, and W_hy is the weight matrix from hidden state to output
        dL_dh_t = dL_dy_hat @ W_hy.T

        # Recursively calculate the gradient for previous hidden states
        for t in reversed(range(T)):
            dL_dh_t += dL_dh_t_plus_1 @ W_hh.T * (1 - h_t ** 2)  # Assuming tanh activation
            dL_dW_hh += dL_dh_t @ h_t_minus_1.T
            dL_db_h += dL_dh_t



**3. Weight Update (Gradient Descent Rule)**
    - Finally, the weights are updated using the gradients calculated above. This is done using the gradient descent rule.

        # Assuming learning_rate is the learning rate
        W_hy -= learning_rate * dL_dW_hy
        W_hh -= learning_rate * dL_dW_hh
        b_h -= learning_rate * dL_db_h


In [57]:
import numpy as np

class CustomRNN:
    def __init__(self, input_size, hidden_size, output_size, learning_rate=0.01):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate

        # Initialize weights
        np.random.seed(42)
        self.W_xh = np.random.randn(hidden_size, input_size)
        self.W_hh = np.random.randn(hidden_size, hidden_size)
        self.W_hy = np.random.randn(output_size, hidden_size)
        self.b_h = np.random.randn(hidden_size, 1)
        self.b_y = np.random.randn(output_size, 1)

    def forward(self, X):
        """ Forward pass through time """
        seq_length = X.shape[0]
        self.h_states = [np.zeros((self.hidden_size, 1))]  # Store hidden states
        self.outputs = []

        for t in range(seq_length):
            h_t = np.tanh(np.dot(self.W_xh, X[t]) + np.dot(self.W_hh, self.h_states[-1]) + self.b_h)
            y_t = np.dot(self.W_hy, h_t) + self.b_y
            self.h_states.append(h_t)
            self.outputs.append(y_t)

        return np.array(self.outputs)

    def backward(self, X, Y, outputs):
        """ Backpropagation Through Time (BPTT) """
        seq_length = X.shape[0]

        # Initialize gradients
        dW_xh, dW_hh, dW_hy = np.zeros_like(self.W_xh), np.zeros_like(self.W_hh), np.zeros_like(self.W_hy)
        db_h, db_y = np.zeros_like(self.b_h), np.zeros_like(self.b_y)
        dh_next = np.zeros((self.hidden_size, 1))

        for t in reversed(range(seq_length)):
            dy = outputs[t] - Y[t]  # Error at output
            dW_hy += np.dot(dy, self.h_states[t+1].T)
            db_y += dy

            # Backpropagate into hidden state
            dh = np.dot(self.W_hy.T, dy) + dh_next
            dh_raw = (1 - self.h_states[t+1]**2) * dh  # tanh derivative
            dW_xh += np.dot(dh_raw, X[t].T)
            dW_hh += np.dot(dh_raw, self.h_states[t].T)
            db_h += dh_raw
            dh_next = np.dot(self.W_hh.T, dh_raw)

        # Update weights
        for param, dparam in zip([self.W_xh, self.W_hh, self.W_hy, self.b_h, self.b_y], 
                                 [dW_xh, dW_hh, dW_hy, db_h, db_y]):
            param -= self.learning_rate * dparam

    def train(self, X, Y, epochs=100):
        """ Train the RNN """
        for epoch in range(epochs):
            outputs = self.forward(X)
            loss = np.mean((outputs - Y) ** 2)  # Mean Squared Error
            self.backward(X, Y, outputs)

            if epoch % 10 == 0:
                print(f"Epoch {epoch}, Loss: {loss:.4f}")

# Define input, hidden, and output sizes
input_size, hidden_size, output_size, seq_length = 3, 5, 2, 4

# Initialize RNN
rnn = CustomRNN(input_size, hidden_size, output_size)

# Sample input and target
X = np.random.randn(seq_length, input_size, 1)
Y = np.random.randn(seq_length, output_size, 1)

# Train the RNN
rnn.train(X, Y, epochs=201)

Epoch 0, Loss: 5.5586
Epoch 10, Loss: 1.6068
Epoch 20, Loss: 1.0345
Epoch 30, Loss: 0.7091
Epoch 40, Loss: 0.4858
Epoch 50, Loss: 0.3457
Epoch 60, Loss: 0.2433
Epoch 70, Loss: 0.1678
Epoch 80, Loss: 0.1156
Epoch 90, Loss: 0.1289
Epoch 100, Loss: 0.1353
Epoch 110, Loss: 0.1073
Epoch 120, Loss: 0.0860
Epoch 130, Loss: 0.0688
Epoch 140, Loss: 0.0548
Epoch 150, Loss: 0.0436
Epoch 160, Loss: 0.0347
Epoch 170, Loss: 0.0277
Epoch 180, Loss: 0.0221
Epoch 190, Loss: 0.0177
Epoch 200, Loss: 0.0142


In [58]:
X

array([[[-0.30921238],
        [ 0.33126343],
        [ 0.97554513]],

       [[-0.47917424],
        [-0.18565898],
        [-1.10633497]],

       [[-1.19620662],
        [ 0.81252582],
        [ 1.35624003]],

       [[-0.07201012],
        [ 1.0035329 ],
        [ 0.36163603]]])

In [59]:
Y

array([[[-0.64511975],
        [ 0.36139561]],

       [[ 1.53803657],
        [-0.03582604]],

       [[ 1.56464366],
        [-2.6197451 ]],

       [[ 0.8219025 ],
        [ 0.08704707]]])

In [60]:
outputs = rnn.forward(X)

In [62]:
outputs

array([[[-0.57034909],
        [ 0.25712017]],

       [[ 1.55243268],
        [-0.03963926]],

       [[ 1.4533344 ],
        [-2.53618708]],

       [[ 0.66825881],
        [ 0.28576962]]])

In [61]:
np.mean((outputs - Y) ** 2)

0.012394317319274125

#### Challenges in RNNs

Recurrent Neural Networks (RNNs) face several challenges, including the vanishing gradient problem, the exploding gradient problem, and difficulties with long-term dependencies. Here are explanations and solutions for each:

**a. Vanishing Gradient Problem**
- During backpropagation, gradients can become very small, causing the weights to update very slowly.
- This makes it difficult for the network to learn long-term dependencies.

**Solutions:**
1. **Long Short-Term Memory (LSTM):**
   - LSTMs use gates to control the flow of information and maintain gradients over long sequences.
2. **Gated Recurrent Units (GRU):**
   - GRUs are a simpler alternative to LSTMs that also help mitigate the vanishing gradient problem.
3. **Gradient Clipping:**
   - Clipping the gradients during backpropagation to prevent them from becoming too small.

**b. Exploding Gradient Problem**
- During backpropagation, gradients can become very large, causing the weights to update too much.
- This can lead to unstable training and divergence.

**Solutions:**
1. **Gradient Clipping:**
   - Clipping the gradients to a maximum value to prevent them from becoming too large.
2. **Weight Regularization:**
   - Applying regularization techniques like L2 regularization to keep the weights small.

**c. Long-Term Dependencies**
- RNNs struggle to learn dependencies that span long sequences due to the vanishing gradient problem.

**Solutions:**
1. **LSTM and GRU:**
   - Both architectures are designed to handle long-term dependencies better than standard RNNs.
2. **Attention Mechanisms:**
   - Attention mechanisms allow the model to focus on relevant parts of the input sequence, improving the handling of long-term dependencies.
3. **Transformer Models:**
   - Transformers use self-attention mechanisms to capture long-term dependencies without relying on sequential processing.

By addressing these challenges with the appropriate techniques, RNNs can be made more effective for various sequence modeling tasks.

### Variants of RNNs

#### Long Short-Term Memory (LSTM)

Long Short-Term Memory (LSTM) is a type of recurrent neural network (RNN) architecture that is well-suited to learning from sequences of data. 

LSTMs are designed to overcome the limitations of traditional RNNs, particularly the problem of vanishing and exploding gradients. They achieve this by incorporating a `memory cell and three gates`: the input gate, the forget gate, and the output gate.

**Components of an LSTM**

1. **Cell State**:
   - The cell state is the memory of the network. 
   - It runs through the entire chain, with only some minor linear interactions. 
   - It allows information to flow unchanged, which helps in preserving long-term dependencies.

2. **Input Gate**:
   - The input gate decides how much of the new information from the current input and the previous hidden state should be added to the cell state. 
   - It consists of a sigmoid layer and a tanh layer.
   - The sigmoid layer outputs values between 0 and 1, which are multiplied by the tanh layer's output to determine the amount of new information to be added.

3. **Forget Gate**:
   - The forget gate decides what information should be discarded from the cell state. 
   - It also consists of a sigmoid layer that outputs values between 0 and 1, which are multiplied by the cell state to determine what to forget.

4. **Output Gate**:
   - The output gate decides what the next hidden state should be. 
   - It uses the cell state and the current input to produce the hidden state for the next time step. 
   - It consists of a sigmoid layer and a tanh layer.
   - The sigmoid layer determines which parts of the cell state to output, and the tanh layer scales the cell state to a value between -1 and 1.

**LSTM Equations**

Here are the equations that define the operations of an LSTM cell:

      # Forget gate
      f_t = sigmoid(np.dot(W_f, [h_{t-1}, x_t]) + b_f)

      # Input gate
      i_t = sigmoid(np.dot(W_i, [h_{t-1}, x_t]) + b_i)
      C̃_t = tanh(np.dot(W_C, [h_{t-1}, x_t]) + b_C)

      # Cell state
      C_t = f_t * C_{t-1} + i_t * C̃_t

      # Output gate
      o_t = sigmoid(np.dot(W_o, [h_{t-1}, x_t]) + b_o)
      h_t = o_t * tanh(C_t)



Where:
- `x_t` is the input at time step `t`.
- `h_{t-1}` is the hidden state from the previous time step.
- `C_{t-1}` is the cell state from the previous time step.
- `W_f`, `W_i`, `W_C`, `W_o` are the weight matrices for the forget gate, input gate, cell state, and output gate, respectively.
- `b_f`, `b_i`, `b_C`, `b_o` are the bias terms for the forget gate, input gate, cell state, and output gate, respectively.
- `sigmoid` and `tanh` are the activation functions.

These components and equations allow LSTMs to maintain and update a memory cell, enabling them to learn long-term dependencies in sequential data.

In [63]:
import numpy as np

class LSTMCell:
    def __init__(self, input_dim, hidden_dim):
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        
        # Initialize weights and biases
        self.W_f = np.random.randn(hidden_dim, hidden_dim + input_dim)
        self.b_f = np.zeros((hidden_dim, 1))
        
        self.W_i = np.random.randn(hidden_dim, hidden_dim + input_dim)
        self.b_i = np.zeros((hidden_dim, 1))
        
        self.W_C = np.random.randn(hidden_dim, hidden_dim + input_dim)
        self.b_C = np.zeros((hidden_dim, 1))
        
        self.W_o = np.random.randn(hidden_dim, hidden_dim + input_dim)
        self.b_o = np.zeros((hidden_dim, 1))
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def tanh(self, x):
        return np.tanh(x)
    
    def forward(self, x_t, h_prev, C_prev):
        # Concatenate hidden state and input
        concat = np.vstack((h_prev, x_t))
        
        # Forget gate
        f_t = self.sigmoid(np.dot(self.W_f, concat) + self.b_f)
        
        # Input gate
        i_t = self.sigmoid(np.dot(self.W_i, concat) + self.b_i)
        C̃_t = self.tanh(np.dot(self.W_C, concat) + self.b_C)
        
        # Cell state
        C_t = f_t * C_prev + i_t * C̃_t
        
        # Output gate
        o_t = self.sigmoid(np.dot(self.W_o, concat) + self.b_o)
        h_t = o_t * self.tanh(C_t)
        
        return h_t, C_t

# Example usage
input_dim = 3  # Example input dimension
hidden_dim = 5  # Example hidden state dimension

lstm = LSTMCell(input_dim, hidden_dim)

# Example input
x_t = np.random.randn(input_dim, 1)
h_prev = np.zeros((hidden_dim, 1))
C_prev = np.zeros((hidden_dim, 1))

h_t, C_t = lstm.forward(x_t, h_prev, C_prev)

print("Hidden state:", h_t)
print("Cell state:", C_t)

Hidden state: [[ 0.10300916]
 [ 0.03630028]
 [-0.49784764]
 [-0.19816366]
 [-0.08696417]]
Cell state: [[ 0.77549715]
 [ 0.0670822 ]
 [-0.65920812]
 [-0.39389873]
 [-0.67070856]]
